<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>csim</string>
	</array>
	<key>name</key>
	<string>CircuitSim</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(inputNames|outputNames|circuit|outputs|truthTable|propagationDelay|circuitInputs|testCase)\b</string>
			<key>name</key>
			<string>support.class.circuit_sim</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b(AND|XOR|OR|NAND|HALF-ADDER|ADDER|FULL-ADDER|SELECTOR|MULTIPLEXER|PASSTHROUGH|WIRE|NOT|NOR|FullAdder|HalfAdder|DECODER|MUX|ALU|SELECT|T_SELECT|SHIT_CONTROL_SELECT|ShiftControlSelect|ShiftLeft|SHIFT_LEFT|ShiftRight|SHIFT_RIGHT|OUTPUT_SELECT|OutputSelect|MAJORITY|MINORITY|CarrySelectAdder|CARRY-SELECT-ADDER|RIPPLE_CARRY_ADDER|RippleCarryAdder|LOGICAL)([0-9]+)\b)</string>
			<key>name</key>
			<string>keyword.control.circuit_sim</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b(AND|XOR|OR|NAND|HALF-ADDER|ADDER|FULL-ADDER|SELECTOR|MULTIPLEXER|PASSTHROUGH|WIRE|NOT|NOR|FullAdder|HalfAdder|DECODER|MUX|ALU|SELECT|T_SELECT|SHIT_CONTROL_SELECT|ShiftControlSelect|ShiftLeft|SHIFT_LEFT|ShiftRight|SHIFT_RIGHT|OUTPUT_SELECT|OutputSelect|MAJORITY|MINORITY|CarrySelectAdder|CARRY-SELECT-ADDER|RIPPLE_CARRY_ADDER|RippleCarryAdder|LOGICAL)\b)</string>
			<key>name</key>
			<string>keyword.control.circuit_sim</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\^|\&amp;|\~|\||\!)</string>
			<key>name</key>
			<string>constant.language.circuit_sim</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\=|\,|\:|\.)</string>
			<key>name</key>
			<string>keyword.control.circuit_sim</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\(|\)|\{|\}|\[|\])</string>
			<key>name</key>
			<string>string.single.circuit_sim</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.circuit_sim</string>
				</dict>
			</dict>
			<key>match</key>
			<string>((#).*)</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.circuit_sim</string>
	<key>uuid</key>
	<string>e2d64bf1-84e4-4029-b11c-647468068da2</string>
</dict>
</plist>
