#!/bin/bash
# This script runs the generates a .txt file from all .csim files and executes
# the CircuitSim program with that as an output.

mkdir -p "`pwd`/out"

if [ ! -f "`pwd`/out/CircuitSim.jar" ]
	then
		echo "Copying Circuit Sim to the output folder"
		cp CircuitSim.jar "`pwd`/out/"CircuitSim.jar
fi

if [ $1 == "-cp" ]
	then
	echo "Convertint files from .csim to .txt ..."
	echo -------------------------------------
	echo 
fi

for var in "$@"
do
	if [[ ! $var = [0-9]* ]] && [[ ! $var == "runScript" ]] && [[ ! $var == "CircuitSim.jar" ]] && [[ ! -d $var ]]
		then

		if [ ! $var == "-cp" ]
			then
			echo "Copying file: $var"

			if [[ ! $var = [csim]* ]]
				then
				cp "$var" "`pwd`/out/""$var".txt
			else
				cp "$var".csim "`pwd`/out/""$var".txt
			fi
		fi
	fi
done

if [ ! $1 == "-cp" ]
	then
	echo
	echo Running CircuitSim with $@
	echo -------------------------------------
	echo 

	cd "`pwd`/out/"
	java -jar CircuitSim.jar $@
fi

echo 