#!/bin/bash
# Author: Marcus Gabilheri
# Check out the readme on github at https://github.com/fnk0/CircuitSimSyntax
# This script runs the generates a .txt file from all .csim files and executes
# the CircuitSim program with that as an output.

mkdir -p "`pwd`/out"

ext=.csim

if [ ! -f "`pwd`/out/CircuitSim.jar" ]
	then
		echo "Copying Circuit Sim to the output folder"
		cp CircuitSim.jar "`pwd`/out/"CircuitSim.jar
fi

if [[ $1 == "" ]]
	then
	echo "Usage: runScript FILE"
	echo "Usage: runScript FILE args"
	echo "Usage: runScript -cp FILES || *"
elif [[ $1 == "-cp" ]]; then
	echo "Converting files from .csim to .txt ..."
	echo -------------------------------------
	echo 
fi

for var in "$@"
do
	if [[ ! $var = [0-9]* ]] && [[ ! $var == "runScript" ]] && [[ ! $var == "CircuitSim.jar" ]] && [[ ! -d $var ]]
		then

		if [ ! $var == "-cp" ]
			then
			file=$(echo $var | sed -e 's/\(.csim\)*$//g')
			echo "Copying file: $file$ext"

			cp $file$ext "`pwd`/out/$var".txt
		fi
	fi
done

if [ ! $1 == "-cp" ]
	then
	echo
	echo Running CircuitSim with $@
	echo -------------------------------------
	echo 

	cd "`pwd`/out/"
	java -jar CircuitSim.jar $@
fi

echo 